#metody operujace na napisach

napis = 'Witaj w Pythonie'

print napis.capitalize()
print napis.center(64)
print napis.center(64,'*')
print napis.count('e')
print napis.find('Taj')
print napis.find('taj')
print napis.isdigit()
print '12'.isdigit()
print '12.4'.isdigit()
print ' '.join(['Python','jest','super'])
print napis.join(['***']*5)
print napis.lower()
print napis.replace('Pythonie', 'Programowanie')
print napis.rfind('Pythonie')
print 'Python jest super'.rfind('e')
print napis.rjust(32)
print napis.rjust(64)
print napis.rjust(64, '.')
print napis.split()
print '123-234-567'.split('-')
print ((napis+'\n')*10).splitlines()
print napis.swapcase()
print napis.title()
print napis.upper()